apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: 698814524746.dkr.ecr.ap-south-1.amazonaws.com/test:v1
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 2
            memory: 3Gi  
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-oodles-host
spec:
  rules:
  - host: "af175adef065f4508a335c0cf8344059-1547841465.ap-south-1.elb.amazonaws.com"
    http:
      paths:
      - pathType: Prefix
        path: "/oodles"
        backend:
          service:
            name: nodeapp-service
            port:
              number: 5000
~                                                                               
~                                                                               
~                                       
